services:
  product-managemant:
      image: node:18-alpine
      container_name: productManagement
      command: sh -c "npm install && npm run start"
      expose:
      - 4500
      ports:
      - 4500:4500
      working_dir: /productManagement
      volumes: 
      - ./product-management:/productManagement
      
      environment:
        PORT: 4500
        NODE_ENV: ${NODE_ENV}
        DATABASE_URL: ${DATABASE_URL}
        SALT_ROUND: ${SALT_ROUND}
        JWT_SECRET: ${JWT_SECRET}
